// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const EvenFibonacciNumbers = () => {
    const startingTerms = [1,2]
    let sumOfEven = 2

    const sequence = (term1, term2) => {
        let sum = term1 + term2
        if (sum < 4000000) {
            if (sum % 2 === 0) {
                sumOfEven += sum
            }
            sequence(term2, sum)
        } else {
            console.log(sumOfEven)            
        }
    }
    sequence(startingTerms[0], startingTerms[1])
}

EvenFibonacciNumbers()
